# simulation frequency
control_freq : 100 
physics_freq : 300 
render_freq  : 10

omnigraph :
  ros_clock_publisher:
    enable : true
    topic  : clock
    freq   : 300

  ros_lidar_publisher :
    enable : true
    topic  : point_cloud
    freq   : 10 # render_freq의 약수여야 함